# Generated by Django 2.1.1 on 2018-09-19 13:26

import api.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254)),
                ('cost', models.FloatField()),
                ('type', enumfields.fields.EnumIntegerField(default=True, enum=api.models.EntryType)),
            ],
            options={
                'db_table': 'registers',
            },
        ),
    ]
